# You can customise the chat messages the plugin sends here. :)
messages:

  # Replaces the first '%prefix%' placeholder in any chat message below.
  prefix: '&b&lLittleThings:&7'

  # When running the main command without any arguments.
  main:
    - ' '
    - '&b&lLittleThings &fv%version% &7by lokka30'
    - ' '
    - '&f&nAvailable Commands:'
    - '&8 &m->&b /%label% &8- &7view the plugin''s commands.'
    - '&8 &m->&b /%label% reload &8- &7reload any config changes.'
    - ' '

  # When running the reload subcommand.
  reload:
    start:
      - '%prefix% Reloading configuration ...'
    finish:
      - '%prefix% ... Reload complete.'

  # When the user incorrectly uses the command.
  usage:
    - '%prefix% Usage: &b/%label% [reload]'

  # When the user does not have permission to run the command.
  no-permission:
    - '%prefix% You don''t have access to that.'

# Send debug spam into the console?
debug: false

# Check for updates on startup? Will warn console once if there is a new version available. (Async too!)
check-for-updates: true

# Do not change this unless you know what you are doing.
file-version: 7